# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://pbs.twimg.com/profile_images/495668870322331648/_vMr7Ztq.jpeg

# Used for Sitemap.xml and your RSS feed
url: http://jschnapf.github.io

# Name of your site (displayed in the header)
name: Joshua Schnapf

# Short bio or description (displayed in the header)
description: Artist, designer

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble: 
  email: schnapf@gmail.com
  facebook: 
  flickr: 
  github: jschnapf
  instagram: schnapf
  linkedin: 
  pinterest: 
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: schnapf
