# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Joshua Schnapf
tagline:          Art + Web
description:      A blog
baseurl:          http://jschnapf.github.io/lanyon/



author:
  name:           'Joshua Schnapf'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           http://jschnapf.github.io/lanyon/
