# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Lanyon
tagline:          'A Jekyll theme'
description:      'A Jekyll blog.'
url:              http://jschnapf.github.io/lanyon/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           http://jschnapf.github.io/lanyon/
